# Generated by Django 4.1.3 on 2023-01-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakuriha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientusers',
            name='patient_password',
            field=models.TextField(max_length=10, verbose_name='パスワード'),
        ),
    ]
