# Generated by Django 4.1.3 on 2023-02-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakuriha', '0002_alter_patientusers_patient_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='diary_mail',
            field=models.BooleanField(default=False, verbose_name='日記メールフラグ'),
        ),
    ]
