# Generated by Django 4.1.3 on 2023-02-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakuriha', '0003_diary_diary_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='diary_mail',
        ),
        migrations.AddField(
            model_name='patientusers',
            name='diary_mail',
            field=models.BooleanField(default=False, verbose_name='日記メールフラグ'),
        ),
    ]
