# Generated by Django 4.1.3 on 2023-02-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakuriha', '0005_remove_patientusers_diary_mail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporterusers',
            name='diary_mail',
        ),
        migrations.AddField(
            model_name='patientusers',
            name='diary_mail',
            field=models.BooleanField(default=True, verbose_name='日記メールフラグ'),
        ),
    ]
